[build]
  publish = "public"
  command = "echo 'Build concluido'"

[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 302

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
