[build]
  publish = "public"
  command = "echo 'Build concluido'"

# Define Landing Page como página inicial SEM redirecionamento
[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200
  force = true
